SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE DATABASE IF NOT EXISTS `pais`;

USE `pais`;

CREATE TABLE IF NOT EXISTS `pais`.`pais`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(100) NOT NULL,
    `populacao` BIGINT NOT NULL,
    `area` DECIMAL(15,2) NOT NULL,
    PRIMARY KEY (`id`)
);

INSERT INTO pais (nome, populacao, area) VALUES ('Afeganistão', 546456, 456456.00);
INSERT INTO pais (nome, populacao, area) VALUES ('Cuba', 66546456, 45645645.00);
INSERT INTO pais (nome, populacao, area) VALUES ('Brasil', 654645, 64654645.00);
INSERT INTO pais (nome, populacao, area) VALUES ('India', 6566460, 45645645.00);
INSERT INTO pais (nome, populacao, area) VALUES ('Bolivia', 64565464, 325464263.00);

SELECT * FROM pais;